---
name: "SLURM"
partition: "accelerated"
job-name: "hopper_jump_tcp"
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 152
time: 300
gpus_per_rep: 1
scheduler: horeka
sbatch_args:
  gres: "gpu:4"

#name: "SLURM"
#partition: "cpuonly"
#job-name: "hopper_jump_tcp"
#num_parallel_jobs: 0
#cpus-per-task: 152
#time: 600
#cpus_per_rep: 38
#scheduler: cpu_distribute
#ntasks: 1

---
name: hopper_jump_tcp
import_path: "./shared.yaml"
import_exp: "hopper_jump_tcp"

# cw2 config
repetitions: 4          # Number of repetitions, each with different random seed, 4 for test, 20 for paper
reps_per_job: 4
reps_in_parallel: 4
iterations: &iterations 3000
num_checkpoints: 1

# Hardware specific parameters
params:
  sampler:
    args:
      num_env_train: 32
      num_env_test: 32
      episodes_per_train_env: 2
      episodes_per_test_env: 2
  projection:
    args:
      total_train_steps: *iterations
