# Global config
exp_name: &exp_name "hopper_jump_tcp"
exp_path: &exp_path "../../mprl_exp_result"
sub_exp_name: &sub_exp_name "gymnasium, control cost, with GAE"
act_func_hidden: &act_func_hidden leaky_relu
act_func_last: &act_func_last null
dtype: &dtype "float64"
#device: &device "cpu"
device: &device "cuda"
seed: auto

# cw2 config
name: *exp_name
path: *exp_path

# wandb
wandb:
  project: *exp_name
  group: *sub_exp_name
  entity: WANDB_USERNAME
  log_interval: &log_interval 25
  log_model: true
  model_name: model

# experiment parameters
params:
  agent:
    type: TemporalCorrelatedAgent
    args:
      lr_policy: 1e-4
      lr_critic: 1e-4
      wd_policy: 5e-5
      wd_critic: 5e-5
      schedule_lr_policy: true
      schedule_lr_critic: true
      clip_critic: 0.0
      clip_grad_norm: 0.0
      entropy_penalty_coef: 0.0
      discount_factor: &discount_factor 1
      gae_scaling: 0.95
      epochs_policy: 50
      epochs_critic: 50
      num_minibatchs: 1
      norm_advantages: true
      clip_advantages: 0.0
      use_gae: true
      segment_advantage: value_subtraction
      set_variance: false
      balance_check: *log_interval
      evaluation_interval: *log_interval
      dtype: *dtype
      device: *device

  mp: &mp
    type: prodmp
    args:
      num_dof: 3
      tau: 0.8
      alpha_phase: 3
      num_basis: 3
      basis_bandwidth_factor: 3
      num_basis_outside: 0
      alpha: 10
      dt: &dt 0.008
      auto_scale_basis: true
      relative_goal: false
      weights_scale: 1
      goal_scale: 1
      dtype: *dtype
      device: *device

  policy:
    type: TemporalCorrelatedPolicy
    args:
      mean_net_args:
        avg_neuron: 128
        num_hidden: 2
        shape: 0.0
      variance_net_args:
        std_only: false
        contextual: false
      init_method: orthogonal
      out_layer_gain: 0.01
      min_std: 1e-4
      act_func_hidden: *act_func_hidden
      act_func_last: *act_func_last
      dtype: *dtype
      device: *device
      mp: *mp

  critic:
    type: ValueFunction
    args:
      hidden:
        avg_neuron: 128
        num_hidden: 2
        shape: 0.0
      init_method: orthogonal
      out_layer_gain: 1
      act_func_hidden: *act_func_hidden
      act_func_last: *act_func_last
      dtype: *dtype
      device: *device

  projection:
    type: KLProjectionLayer
    args:
      proj_type: kl
      mean_bound: 0.1
      cov_bound: 0.02
      trust_region_coeff: 1.0
      scale_prec: true
      entropy_schedule: false  # Desired value is linear or exp or None
      target_entropy: 0.0 # target entropy per action dim
      temperature: 0.7
      entropy_eq: false # If the entropy should follow an equality constraint
      entropy_first: false # If the entropy should be the first constraint
      do_regression: false
      dtype: *dtype
      device: *device

  sampler:
    type: TemporalCorrelatedSampler
    args:
      env_id: "fancy_ProDMP_TCE/HopperJumpSparse-v0"
      norm_step_obs: true
      time_pairs_config:
        num_select: 25
        fixed_interval: true
      dtype: *dtype
      device: *device
      seed: auto
      task_specified_metrics: ["max_height", "goal_dist", "height_rew", "healthy_reward"]