# cw2 config
name: table_tennis_4d_bbrl
import_path: "./shared.yaml"
import_exp: "table_tennis_4d_bbrl"

repetitions: 1
reps_per_job: 1
reps_in_parallel: 1
iterations: &iterations 7500
num_checkpoints: 1

# Hardware specific parameters
params:
  sampler:
    args:
      num_env_train: 8
      num_env_test: 8
      episodes_per_train_env: 2
      episodes_per_test_env: 1
  projection:
    args:
      total_train_steps: *iterations